[package]
name = "string_algorithms"
description = "crate containing a variety of string algorithms"
version = "0.1.0"
edition = "2021"
authors = ["Arnab De <arkrde@gmail.com>", "Debomita Saha De <debomitasaha@gmail.com>"]
license-file = "LICENSE"
categories = ["algorithms"]